language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3.3-5.2-alpha1"

install: pip install -r test-requirements.txt

script: py.test tests --cov=./reobject
after_success: codecov
