language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"

before_install:
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.3-5.5-alpha-20161013-linux_x86_64-portable.tar.bz2 && tar -jxvf pypy3.3-5.5-alpha-20161013-linux_x86_64-portable.tar.bz2 && echo 'Setting up aliases...' && export PATH=$HOME/pypy3.3-5.5-alpha-20161013-linux_x86_64-portable/bin/:$PATH && ln -s ~/pypy3.3-5.5-alpha-20161013-linux_x86_64-portable/bin/pypy3.3 ~/bin/python && echo 'Setting up pip...' && pypy3.3-5.5-alpha-20161013-linux_x86_64-portable/bin/pypy -m ensurepip && ln -s ~/pypy3.3-5.5-alpha-20161013-linux_x86_64-portable/bin/pip3.3 ~/bin/pip ; fi"

install: pip install -r test-requirements.txt

script: py.test tests --cov=./reobject
after_success: codecov
