language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install: pip install -r test-requirements.txt

script:
  - py.test tests --cov=./reobject
  - py.test examples

after_success: codecov
